ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'DELETE_USER';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'CHANGE_PROJECT_STATUS';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'FLAG_PROJECT';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'UNFLAG_PROJECT';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'FEATURE_PROJECT';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'UNFEATURE_PROJECT';
ALTER TYPE admin_action ADD VALUE IF NOT EXISTS 'UPDATE_PROJECT_NOTE';
